In [1]:
import numpy as np

In [3]:
#create a list comprising numbers from 0 to 9
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
#converting integers to string - this style of handling lists is known as list comprehension.
#List comprehension offers a versatile way to handle list manipulations tasks easily. We'll learn about them in future tutorials. Here's an example.  

[str(c) for c in L]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

[type(item) for item in L]
[int, int, int, int, int, int, int, int, int, int]

[int, int, int, int, int, int, int, int, int, int]

In [8]:
import pandas as pd
#create a data frame - dictionary 
#is used here 
#where keys get 
#converted to column names 
#and values to row values.
data = pd.DataFrame({'Student': 
    ['S1','S2','S3','S4','S5'],
 'Rank':[121,40,100,130,10]})
data

Student  Rank
0      S1   121
1      S2    40
2      S3   100
3      S4   130
4      S5    10

In [9]:
#We can do a quick analysis of any data set using:
data.describe()

Rank
count    5.000000
mean    80.200000
std     52.632689
min     10.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [11]:
#creating arrays
np.zeros(10, dtype='int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [14]:
#create an array with a set sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
#create an array of even space between the given range of values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

array([[-0.18491893, -1.99906929, -0.06898461],
       [-0.24169773,  0.34322317, -1.21550388],
       [ 0.17809567, -0.29749847,  1.10050746]])

In [17]:
#create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [21]:
#assess value to index zero
x1[0]

4

In [19]:
#assess fifth value
x1[4]

8

In [20]:
x1[-1]

4

In [26]:
#in a multidimensional array, we need to specify row and column index
x2=np.array(
[[3, 7, 5, 5],
      [0, 1, 5, 9],
      [3, 0, 5, 0]])


In [27]:
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [28]:
#1st row and 2nd column value
x2[2,3]

0

In [29]:
#3rd row and last value from the 3rd column
x2[2,-1]

0

In [30]:
#replace value at 0,0 index
x2[0,0] = 12

In [32]:
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

In [33]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#from start to 4th position
x[:5]

array([0, 1, 2, 3, 4])

In [35]:
#from 4th position to end
x[4:]

array([4, 5, 6, 7, 8, 9])

In [36]:
#from 4th to 6th position
x[4:7]

array([4, 5, 6])

In [37]:
#return elements at even place
x[ : : 2]

array([0, 2, 4, 6, 8])

In [39]:
#return elements from first position step by two
x[1::2]

array([1, 3, 5, 7, 9])

In [40]:
#reverse the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
#You can concatenate two or more arrays at once.
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [42]:
#You can also use this function to create 2-dimensional arrays.
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [43]:
#Using its axis parameter, you can define row-wise or column-wise matrix
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [44]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [45]:
#Similarly, you can add an array using np.hstack
z = np.array([[9],[9]])
np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

In [46]:
#Also, we can split the arrays based on pre-defined positions.
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x1,x2,x3 = np.split(x,[3,6])
x1

array([0, 1, 2])

In [49]:
x2

array([3, 4, 5])

In [50]:
x3

array([6, 7, 8, 9])

In [51]:
#create a data frame - dictionary is used here where keys get converted to column names and values to row values.
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [52]:
#We can do a quick analysis of any data set using:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [56]:
data.corr()

Rank
Rank   1.0

In [58]:
#Among other things, it shows
#the data set has 5 rows and 
#2 columns with their 
#respective names.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [59]:
#Let's create another data frame.
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [61]:
#Let's sort the data frame by ounces - inplace = True will make changes to the data
data.sort_values(by=['ounces','group'],ascending=True,inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [62]:
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [63]:
#create another data with duplicated rows
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [64]:
#sort values 
data.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [65]:
#remove duplicates - ta da! 
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [69]:
data.corr()

ounces
ounces     1.0

In [66]:
data.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

In [67]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [81]:
import math

def std_dev(data):
    n = len(data)
    mean = sum(data) / n
    deviations = [(x - mean) ** 2 for x in data]
    variance = sum(deviations) / n
    return math.sqrt(variance)

In [82]:
std_dev(data)

0.8660254037844386

In [79]:
import statistics

data = [2, 2, 2, 4]
mean = sum(data) / len(data)

std_dev = statistics.stdev(data)
print(mean)
print(std_dev)


2.5
1.0


In [75]:
mean= 10/4
mean

2.5

In [76]:
.25+.25+.25 

0.75

In [77]:
2.5-4 

-1.5

In [80]:
1.5*1.5

2.25

In [83]:
3/4

0.75

In [ ]:
data = [1, 2, 3, 4, 5]
mean = sum(data) / len(data)

print(mean)

In [84]:
import pandas as pd
data = [
    {
        "company": "Google",
        "tagline": "Dont be evil",
        "management": {"CEO": "Sundar Pichai"},
        "department": [
            {"name": "Gmail", "revenue (bn)": 123},
            {"name": "GCP", "revenue (bn)": 400},
            {"name": "Google drive", "revenue (bn)": 600},
        ],
    },
    {
        "company": "Microsoft",
        "tagline": "Be What's Next",
        "management": {"CEO": "Satya Nadella"},
        "department": [
            {"name": "Onedrive", "revenue (bn)": 13},
            {"name": "Azure", "revenue (bn)": 300},
            {"name": "Microsoft 365", "revenue (bn)": 300},
        ],
    },
  
]
result = pd.json_normalize(
    data, "department", ["company", "tagline", ["management", "CEO"]]
)
result

name  revenue (bn)    company         tagline management.CEO
0          Gmail           123     Google    Dont be evil  Sundar Pichai
1            GCP           400     Google    Dont be evil  Sundar Pichai
2   Google drive           600     Google    Dont be evil  Sundar Pichai
3       Onedrive            13  Microsoft  Be What's Next  Satya Nadella
4          Azure           300  Microsoft  Be What's Next  Satya Nadella
5  Microsoft 365           300  Microsoft  Be What's Next  Satya Nadella

In [92]:
data ='''[{
    "company": "XYZ",
    "employees": [
        {
            "name": "John",
            "department": [
                {"name": "Sales", "role": "Manager"},
                {"name": "Marketing", "role": "Associate"},
            ]
        },
        {
            "name": "Jane",
            "department": [
                {"name": "Engineering", "role": "Engineer"},
                {"name": "Product", "role": "Manager"},
            ]
        }
    ]
}
]
'''

In [91]:
result = pd.json_normalize(
    data )

NotImplementedError: 

In [87]:
dataa = json.load(data)

NameError: name 'json' is not defined